name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: 'none'

environment:
  sdk: ^3.5.0-edge.fb057ea4e07de2af624688455925c0ca07afe04f

# Add regular dependencies here.
dependencies:
  catwalk:
    path: ../packages/catwalk
  catwalk_server:
    path: ../packages/catwalk_server


dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
