name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: 'none'

environment:
  sdk: ^3.5.0-155.0.dev

# Add regular dependencies here.
dependencies:
  catwalk:
    path: ../packages/catwalk
  catwalk_server:
    path: ../packages/catwalk_server

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.13
  catwalk_generator:
    path: ../packages/catwalk_generator

dependency_overrides:
  catwalk:
    path: ../packages/catwalk