name: catwalk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-edge.fb057ea4e07de2af624688455925c0ca07afe04f

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  lyell: ^1.1.0

  conduit_open_api: ^4.4.0
  conduit_codable: ^4.4.0
  http: ^1.2.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
