targets:
  $default:
    builders: {}

builders:
  definitions_descriptor:
    import: "package:catwalk_generator/integrations.dart"
    builder_factories: [ "definitionsDescriptor" ]
    build_extensions: { ".dart": [ ".endpoint.catwalk" ] }
    runs_before: [ "catwalk_generator:definitions_subject" ]
    auto_apply: dependents
    build_to: cache
    applies_builders:
      - catwalk_generator|client_builder
  definitions_subject:
    import: "package:catwalk_generator/integrations.dart"
    builder_factories: [ "definitionsSubject" ]
    build_extensions: { ".dart": [ ".endpoint.g.dart" ] }
    auto_apply: dependents
    build_to: source
    applies_builders:
      - catwalk_generator|client_builder
  catwalk_reactor:
    import: "package:catwalk_generator/integrations.dart"
    builder_factories: [ "reactorBuilder" ]
    build_extensions: { "$lib$": [ "catwalk.g.dart" ] }
    required_inputs: [ ".endpoint.catwalk",".endpoint.g.dart" ]
    auto_apply: dependents
    build_to: source
    applies_builders:
      - catwalk_generator|client_builder