name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-155.0.dev

# Add regular dependencies here.
dependencies:
  catwalk: any
  lyell: ^1.1.0
  catwalk_macros: any

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.11
  catwalk_polyfills: any

dependency_overrides:
  catwalk:
    path: ../../packages/catwalk
  catwalk_polyfills:
    path: ../../packages/catwalk_polyfills
  catwalk_macros:
    path: ../../packages/catwalk_macros